    select DISTINCT AWRKHISSUI.CPY_0 as societe,AUTILIS.NOMUSR_0 as demandeur,AUTILIS.ADDEML_0 as email,
    PREQUISD.YDOSSIER_0 as dossier, CLEOBJ_0 as numero_piece,
    left(CAST(PREQUISD.CREDAT_0 as date),10) as 'DATE DEMANDE',
    APLSTD.LANMES_0 AS direction,
    sum(PREQUISD.LINATIAMT_0) as montant, 
    CASE
    WHEN PREQUIS.APPFLG_0 <> 3 THEN 'NON'
    WHEN PREQUIS.APPFLG_0 = 3 THEN 'TOTALEMENT'
    END as signature, AOBJTXT.NAM_0 as lien_pj,AWRKHISSUI.DEST_0 as validateur
    from HABIBO.AWRKHISSUI 
    INNER JOIN HABIBO.PREQUISD on AWRKHISSUI.CLEOBJ_0 = PREQUISD.PSHNUM_0
    INNER JOIN HABIBO.PREQUIS on PREQUISD.PSHNUM_0 = PREQUIS.PSHNUM_0
    INNER JOIN HABIBO.ITMMASTER on PREQUISD.ITMREF_0 = ITMMASTER.ITMREF_0
    LEFT JOIN HABIBO.AOBJTXT on PREQUIS.PSHNUM_0 = AOBJTXT.IDENT1_0
    INNER JOIN HABIBO.APLSTD on PREQUISD.YDIRECTION_0 = APLSTD.LANNUM_0 and LANCHP_0 = 6002
    INNER JOIN HABIBO.AUTILIS on PREQUIS.REQUSR_0 = AUTILIS.USR_0
    where  ABROBJ_0 = 'PSH' 
    and PREQUIS.APPFLG_0 <> 3 and ACTSIG_0 <> 'REJ'
    GROUP BY AWRKHISSUI.CPY_0,AUTILIS.NOMUSR_0,AUTILIS.ADDEML_0,PREQUISD.YDOSSIER_0,CLEOBJ_0,
    APLSTD.LANMES_0,PREQUIS.APPFLG_0,AWRKHISSUI.DEST_0